
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mobile
  password: 123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mobile_db

test:
  <<: *default
  database: mobile_test

production:
  <<: *default
  database: mobile_production
  username: mobile
  password: <%= ENV['MOBILE_DATABASE_PASSWORD'] %>
